baseURL = "https://geektree0101.github.io/"
title = "Geektree0101's website"
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Hyeonsu Ha"
author = "Geektree0101"
description = """
저는 Product Engineer이자 iOS App을 개발하고 있어요 
제품설계, 가치전달, 협업문화에 대해 많은 관심을 가지고있어요.

I'm a Product Engineer & iOS software engineer.
I'm interested in product structure design, product value communication, and collaboration culture.

我是Product Engineer和iOS软件工程师。
我对产品结构设计、产品价值沟通、合作文化感兴趣。
"""
profilePicture = "https://avatars.githubusercontent.com/u/19504988?v=4"

[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/hyeonsu-ha-7ba02b112/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "h2s1880@gmail.com"

[[params.socialIcons]]
icon = "fab fa-github"
title = "github"
url = "https://github.com/GeekTree0101"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "instagram"
url = "https://www.instagram.com/geektree0101/"

[menu]
  [[menu.main]]
  name = "Index 0"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Index 1"
  identifier = "gallery"
  weight = 100
  url = "/gallery/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"