theme = "hugo-theme-minos"
title = "Geektree0101"
author = "Geektree0101"
paginate = 20


[[Menus.main]]
name = "Tags"
url = "/tags"

[[Menus.main]]
name = "Categories"
url = "/categories"

[[Menus.main]]
name = "About"
url = "/about"