theme = "hugo-theme-minos"
title = "Geektree0101"
author = "Geektree0101"
paginate = 20
disqusShortname = "https-geektree0101-github-io"

[[Menus.main]]
name = "Tags"
url = "/tags"

[[Menus.main]]
name = "Categories"
url = "/categories"

[[Menus.main]]
name = "About"
url = "/about"

[params]
  customCSS = ["css/article-toc.css"]